# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "LLM-managed personal knowledge base tooling"
  homepage "https://github.com/oliver-kriska/scribe"
  version "0.2.11"
  license "MIT"

  depends_on "git"
  depends_on "neilberkman/tap/ccrider"
  depends_on "sqlite"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.2.11/scribe_0.2.11_darwin_amd64.tar.gz"
      sha256 "dad2b8cb50fc5f780e613d02723d05de1e155071507d7bef2f433cebd04152aa"

      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.2.11/scribe_0.2.11_darwin_arm64.tar.gz"
      sha256 "3ad15a5a70319a8f58b19410bc9851ee10284e76c6b3e6a565fdb18bde6856c3"

      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.2.11/scribe_0.2.11_linux_amd64.tar.gz"
      sha256 "bea805738cf8250a7525180ad8313487fd6be34a47c76a41ebb5e93fa2d1c2cd"
      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.2.11/scribe_0.2.11_linux_arm64.tar.gz"
      sha256 "49ae63c4f6d2ff2e8056a7d8b1ebd972af9a92d218024f76a2ee03fcc6db09ce"
      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  def post_install
    return unless OS.mac?
    ohai "Homebrew upgraded scribe."
    ohai "If iMessage capture was working before, macOS Full Disk Access"
    ohai "is now invalidated (TCC is keyed to the binary cdhash, not the"
    ohai "install path). Re-run:  scribe fda"
  end

  def caveats
    <<~EOS
      Runtime dependencies not on Homebrew — install these separately:
        * claude     (Claude Code CLI)
                     curl -fsSL https://claude.ai/install.sh | bash
        * qmd        (semantic search over the KB)
                     npm install -g @tobilu/qmd
        * trafilatura (optional, URL → markdown)
                     pipx install trafilatura
        * jq, fzf    (optional)
                     brew install jq fzf

      Already installed by brew as dependencies: git, sqlite, ccrider.

      After installing:
        scribe init --path ~/my-kb
        scribe cron install           # macOS: LaunchAgents
                                      # Linux: prints crontab lines

      macOS — Full Disk Access for `scribe capture` (iMessage):
        scribe fda                    # opens the FDA pane and walks you through
                                      # drag-and-drop from Finder is the most
                                      # reliable method on macOS 14+

      Heads-up: until scribe ships with Developer ID codesigning, the FDA
      grant is tied to the Cellar path + binary cdhash, which both change
      on every `brew upgrade scribe`. After an upgrade, `scribe capture`
      will start failing with "operation not permitted" — just re-run
      `scribe fda`. `scribe doctor` flags this situation explicitly.
    EOS
  end

  test do
    assert_match "scribe", shell_output("#{bin}/scribe --help 2>&1")
  end
end
