# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Scribe < Formula
  desc "LLM-managed personal knowledge base tooling"
  homepage "https://github.com/oliver-kriska/scribe"
  version "0.1.4"
  license "MIT"

  depends_on "git"
  depends_on "sqlite"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.1.4/scribe_0.1.4_darwin_amd64.tar.gz"
      sha256 "6950a59753b8e914f2a5fbd67f73128c16bc85769851ba78f1024f293d9fdfb3"

      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.1.4/scribe_0.1.4_darwin_arm64.tar.gz"
      sha256 "154957b823ed3ff6e68b408f7db1d727165e74f79b61bc74de4d4093c9f6cb35"

      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.1.4/scribe_0.1.4_linux_amd64.tar.gz"
      sha256 "9f275a27d8c74bb4bf8d90eff7ece9977dc6d42936c39b46631a22252f04be2e"
      define_method(:install) do
        bin.install "scribe"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/oliver-kriska/scribe/releases/download/v0.1.4/scribe_0.1.4_linux_arm64.tar.gz"
      sha256 "e34428f061abbf62060583d89487e56b0ace49f67ff495b4f766050a8e684057"
      define_method(:install) do
        bin.install "scribe"
      end
    end
  end

  def caveats
    <<~EOS
      scribe expects several runtime dependencies beyond brew-installed ones:
        * claude     (Claude Code CLI)
        * ccrider    (Claude session recorder)
        * qmd        (semantic search over the KB)
        * trafilatura, jq, fzf (optional)

      After installing:
        scribe init --path ~/my-kb
        scribe cron install
        # macOS: grant Full Disk Access to the scribe binary for capture.
    EOS
  end

  test do
    assert_match "scribe", shell_output("#{bin}/scribe --help 2>&1")
  end
end
